# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: namenode-entrypoint
  namespace: default
data:
  entrypoint.sh: |
    #!/usr/bin/env bash

    set -e

    nn="$(hostname -f | sed 's/\([^\.]*\).*/\1/')"

    if [[ ! -d /data/hadoop ]]; then
      if [[ "${nn}" == 'nn-0' ]]; then
        hdfs namenode -format
      else
        hdfs namenode -bootstrapStandby
      fi
    fi

    {
      while true; do
        content="$(hdfs haadmin -getAllServiceState 2>/dev/null | awk '{print $NF}')"
        if echo "${content}" | grep 'active' &>/dev/null; then
          break
        elif [[ "$(echo "${content}" | grep 'standby' | wc -l)" -eq {{ .Values.global.num_namenode_replicas }} ]]; then
          hdfs haadmin -transitionToActive "${nn}"
        fi
      done
    } &

    hdfs namenode
