# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-conf
  namespace: default
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
            <name>fs.defaultFS</name>
            <value>hdfs://hadoop-cluster</value>
        </property>
    </configuration>

  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
            <name>dfs.nameservices</name>
            <value>hadoop-cluster</value>
        </property>
        <property>
            <name>dfs.ha.namenodes.hadoop-cluster</name>
            {{- $nn_list := list }}
            {{- range $i := until (int .Values.global.num_namenode_replicas) }}
              {{- $nn_list = append $nn_list (printf "nn-%d" $i) }}
            {{- end }}
            <value>{{- join "," $nn_list }}</value>
        </property>
        {{- range $i := until (int .Values.global.num_namenode_replicas) }}
        <property>
            <name>dfs.namenode.rpc-address.hadoop-cluster.nn-{{- $i }}</name>
            <value>nn-{{- $i }}.namenode.default.svc.cluster.local:8020</value>
        </property>
        <property>
            <name>dfs.namenode.http-address.hadoop-cluster.nn-{{- $i }}</name>
            <value>nn-{{- $i }}.namenode.default.svc.cluster.local:50070</value>
        </property>
        {{- end }}
        <property>
            <name>dfs.namenode.shared.edits.dir</name>
            {{- $jn_list := list }}
            {{- range $i := until (int .Values.global.num_journalnode_replicas) }}
              {{- $jn_list = append $jn_list (printf "jn-%d.journalnode:8485" $i) }}
            {{- end }}
            <value>qjournal://{{- join ";" $jn_list }}/hadoop-cluster</value>
        </property>
        <property>
            <name>dfs.client.failover.proxy.provider.hadoop-cluster</name>
            <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
        </property>
        <property>
            <name>dfs.journalnode.edits.dir</name>
            <value>/data/journal/node/local/data</value>
        </property>
        <property>
            <name>dfs.datanode.data.dir</name>
            <value>file:///data/dfs/data</value>
        </property>
        <property>
            <name>hadoop.tmp.dir</name>
            <value>/data/hadoop/tmp</value>
        </property>
    </configuration>
