# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dn
  namespace: default
spec:
  selector:
    matchLabels:
      app: datanode
  serviceName: datanode
  replicas: {{ .Values.global.num_datanode_replicas }}
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - name: dn
          image: {{ .Values.global.image }}
          imagePullPolicy: Never
          env:
            - name: HADOOP_ROOT_LOGGER
              value: INFO,DRFA,console
          command:
            - hdfs
            - datanode
          volumeMounts:
            - name: hdfs-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hdfs-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: datanode-data
              mountPath: /data
      volumes:
        - name: hdfs-conf
          configMap:
            name: hdfs-conf
  volumeClaimTemplates:
    - metadata:
        name: datanode-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.global.storage.datanode_size }}
