# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hs
  namespace: default
spec:
  selector:
    matchLabels:
      app: historyserver
  serviceName: historyserver
  template:
    metadata:
      labels:
        app: historyserver
    spec:
      containers:
        - name: hs
          image: {{ .Values.global.image }}
          imagePullPolicy: Never
          env:
            - name: HADOOP_ROOT_LOGGER
              value: INFO,DRFA,console
          command:
            - mapred
            - historyserver
          volumeMounts:
            - name: yarn-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
            - name: yarn-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
            - name: hdfs-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hdfs-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/core-site.xml
              subPath: core-site.xml
      volumes:
        - name: yarn-conf
          configMap:
            name: yarn-conf
        - name: hdfs-conf
          configMap:
            name: hdfs-conf
